import type { Metadata } from "next";
import TabNavigation from '@/components/TabNavigation';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="p-4"
      >
        <TabNavigation />
        <main className = "mt-6">{children}</main>
      </body>
    </html>
  );
}
