name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}         # usually 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }}           # private key contents
          script: |
            set -e
            # sanity: ensure folder exists
            [ -d /opt/mem-study/mem_study ] || { echo "missing /opt/mem-study/mem_study"; exit 1; }
            # deploy (same as your manual command)
            NEXT_PUBLIC_SOCKET_URL=https://cardsapp.org /opt/mem-study/deploy.sh
