name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Frontend
      - name: Setup Node (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: mem-study-next/package-lock.json
      - name: Install & Build (frontend)
        working-directory: mem-study-next
        run: |
          npm ci
          NEXT_PUBLIC_SOCKET_URL=http://localhost:4000 npm run build

      # Backend
      - name: Setup Node (backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install & Build (backend)
        working-directory: backend
        run: |
          npm ci
          npm run build || echo "no backend build step, skipping"

      # Secrets scan (gitleaks)
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact

      # Docker build check (ensures Dockerfiles compile)
      - name: Docker build (frontend)
        run: docker build -t test-frontend ./mem-study-next
      - name: Docker build (backend)
        run: docker build -t test-backend ./backend

      # Optional: Trivy scan filesystem (quick)
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0
